name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.127.136.136 >> ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to remote server (exclude ./app/dist)
        run: |
          rsync -avz --exclude 'app/dist' --exclude '.git' ./ ubuntu@3.127.136.136:/home/ubuntu/deploy_app/

      - name: Copy files into container
        run: |
          ssh ubuntu@3.127.136.136 << 'EOF'
            
            # Copy files into container (adjust paths accordingly)
            sudo docker cp /home/ubuntu/deploy_app/. c3707db18486:/app
            # rsync -av --progress /home/ubuntu/deploy_app/. -e "sudo docker exec -i" c3707db18486:/app
            # Restart gunicorn inside container
            sudo docker stop c3707db18486
            sudo docker start c3707db18486
          EOF
